In [2]:
from datetime import datetime
from time import sleep
import urllib.request
from bs4 import BeautifulSoup
import re
import pandas as pd
from pandas import Series, DataFrame

""" DFの最大出力行数を50から80へ """
pd.set_option("display.max_rows", 80)

cc = {}
cc['札幌'] = '01'
cc['函館'] = '02'
cc['福島'] = '03'
cc['新潟'] = '04'
cc['東京'] = '05'
cc['中山'] = '06'
cc['中京'] = '07'
cc['京都'] = '08'
cc['阪神'] = '09'
cc['小倉'] = '10'

rc = {}
rc['中山sat'] = cc['中山'] + '0403'
rc['中山sun'] = cc['中山'] + '0404'
rc['中山mon'] = cc['中山'] + '0405'
rc['阪神sat'] = cc['阪神'] + '0403'
rc['阪神sun'] = cc['阪神'] + '0404'
rc['阪神mon'] = cc['阪神'] + '0405'

def myEntriesDF( race_code):

    """ データ取得 """
    entries1_html = urllib.request.urlopen("https://keiba.yahoo.co.jp/race/denma/19" + race_code + "/?page=1")
    entries1_soup = BeautifulSoup(entries1_html,"lxml")
    df1 = pd.io.html.read_html(entries1_soup.prettify())
    entries1_df = df1[2]
    sleep(1)

    entries2_html = urllib.request.urlopen("https://keiba.yahoo.co.jp/race/denma/19" + race_code + "/?page=2")
    entries2_soup = BeautifulSoup(entries2_html,"lxml")
    df2 = pd.io.html.read_html(entries2_soup.prettify())
    entries2_df = df2[2]
    sleep(1)

    entries3_html = urllib.request.urlopen("https://keiba.yahoo.co.jp/race/denma/19" + race_code + "/?page=3")
    entries3_soup = BeautifulSoup(entries3_html,"lxml")
    df3 = pd.io.html.read_html(entries3_soup.prettify())
    entries3_df = df3[2]
    sleep(1)

    """ レース基本情報 """
    race_no = entries1_soup.find_all("td", attrs={'id':'raceNo'}) # <td id="raceNo">
    race_no = re.sub(r"[ \n\[\]]","",str(race_no))
    race_no = re.sub(r"<[^>]*?>","",str(race_no))
    # print(race_no)
    race_name = entries1_soup.find_all("h1",class_="fntB")
    race_name = re.sub(r"<[^>]*?>","",str(race_name))
    race_name = re.sub(r"[ \n\[\]]","",str(race_name))
    race_name = re.sub(r"—","-",str(race_name)) # 大阪-ハンブルグカップ対策
    race_name = re.sub(r"〜","-",str(race_name)) # 19XX-19XXsダービーメモリーズ対策
    race_name = re.sub(r"第.*?回","",str(race_name)) # 重賞の回次を削除
    # print(race_name)
    info_basic = entries1_soup.find_all("p",class_="fntSS",attrs={'id':'raceTitDay'})
    info_basic = re.sub(r"[ \n\[\]]","",str(info_basic))
    info_basic = re.sub(r"<[^>]*?>","",str(info_basic))
    info_basic = info_basic.split("|") # |をデリミタとしてリスト化
    start_time = info_basic.pop(2)
    info_basic.append(race_no)
    info_basic.append(race_name)
    info_basic.append(start_time)

    info_meta = entries1_soup.find_all("p",class_="fntSS gryB",attrs={'id':'raceTitMeta'})
    info_meta = re.sub(r"<img alt=""","",str(info_meta)) # 天気: 馬場:
    info_meta = re.sub(r" border=""","<",str(info_meta))# :雨 :良
    info_meta = re.sub(r"<[^>]*?>","",str(info_meta)) # <と中の^>（でない）文字の繰り返しと>
    info_meta = re.sub(r"\"","",str(info_meta)) # "雨" "良"の(")の削除
    info_meta = re.sub(r"[ \n\[\]]","",str(info_meta))
    info_meta = info_meta.split("|") # |をデリミタとしてリスト化
    #print(info_basic)
    #print(info_meta)
    info_race = info_basic + info_meta

    """ 1) 出走場基本情報 """
    HrsInfo = []
    for h in range(len(entries1_df)):
        horse_number = str(entries1_df.iloc[[h], [1]].values[0][0]).rjust(2,"0")
        horse_name = str(entries1_df.iloc[[h], [2]].values[0][0]).split(" ")[0]
        sex_age = re.sub("  "," ",str(entries1_df.iloc[[h], [2]].values[0][0])).split(" ")[1].split("/")[0]
        weight = str(entries1_df.iloc[[h], [3]].values[0][0]).replace("  ", "")
        jockey = str(entries1_df.iloc[[h], [4]].values[0][0]).split("  ")[0]
        wei_carry = str(entries1_df.iloc[[h], [4]].values[0][0]).split("  ")[1]
        all_result = str(entries1_df.iloc[[h], [6]].values[0][0]).split("  ")[0]
        graded_result = str(entries1_df.iloc[[h], [6]].values[0][0]).split("  ")[1]
        prize = str(entries1_df.iloc[[h], [6]].values[0][0]).split("  ")[2]
        HrsInfo.append([horse_number, horse_name, sex_age, weight, jockey, wei_carry, all_result, graded_result, prize, ' '])
    #print(HrsInfo[0])

    """ 1-1) 前走のレースと着順 """
    lastRuns = entries2_soup.find_all(class_=re.compile("denmaLs mgnBL"))
    lastRuns = str(lastRuns).split("<td class=\"fntN\">") # 馬ごとのコード
    title_ls =[]
    order_ls =[]
    for i in range(1, len(lastRuns)): # lastRuns[0] 表のヘッダを除く 頭数
        ls = lastRuns[i].split("<div class=") # レースごとのコード
        ls = [re.sub(r"\n","", str(ls[j])) for j in range(1, len(ls))] # ls[0] の馬情報を除く
        """ 前走のレース名 """
        titles = [re.search(r"<strong>(.*?)</strong>", str(ls[j][12:90])).group(1) for j in range(len(ls))]
        titles = titles[::-1] # 反転
        if(len(titles)<5): # データなしNaN
            nan = 5 - len(titles)
            for n in range(nan):
                titles.append('')
        title_ls.append(titles)
        """ 前走の着順 """
        orders = [ls[j][12:14] for j in range(len(ls))]
        orders = orders[::-1] # 反転
        for i in range(len(orders)):
            if(orders[i].isdecimal()):
                orders[i] = orders[i] + "着"
            else:
                orders[i] = "xx着"

        if(len(orders)<5): # データなしNaN
            nan = 5 - len(orders)
            for n in range(nan):
                orders.append('') # NaN
        order_ls.append(orders)

    OdrTitle = []
    for h in range(len(entries2_df)):
        ls = [order_ls[h][r] + " " + title_ls[h][r] for r in range(5)]
        OdrTitle.append(ls)

    NameOdrTitle =[]
    for h in range(len(entries2_df)):
        NameOdrTitle.append(HrsInfo[h] + OdrTitle[h])

    #print(NameOdrTitle[0])

    """ 1-2) 馬体重・騎手 """
    WeightJockey=[]
    for h in range(len(entries2_df)):
        ls = []
        for r in [8, 7, 6, 5, 4]:
            etr2 = str(re.sub(" - ","-", str(entries2_df.iloc[[h], [r]].values[0][0]))) # 馬体重の( - )
            etr2 = re.sub("  ", " ", etr2)
            if(etr2 == 'nan'):
                elm = ''
            elif(len(etr2.split(" ")) < 8):
                elm = etr2.split(" ")[4] # ずれた騎手名（競走除外or中止）
            else:
                elm = etr2.split(" ")[7] + " " + etr2.split(" ")[5]  + " " + etr2.split(" ")[6] # 体重・騎手・斤量
            ls.append(elm)
        WeightJockey.append(ls)

    NameWeiJockey =[]
    for h in range(len(entries2_df)):
        NameWeiJockey.append(HrsInfo[h] + WeightJockey[h])

    #print(NameWeiJockey[0])

    """ 1-3) 過去５走コース・タイム """
    #print(NameWeiJockey[0])
    CourseTime= []
    for h in range(len(entries2_df)):
        ls =[]
        for r in [8, 7, 6, 5, 4]:
            etr2 = str(re.sub(" - ","-", str(entries2_df.iloc[[h], [r]].values[0][0]))) # 馬体重の( - )
            etr2 = re.sub("  ", " ", etr2)
            if(etr2 == 'nan'):
                elm = ''
            elif(len(etr2.split(" ")) < 8):
                elm = etr2.split(" ")[2] + " " + etr2.split(" ")[3] # 競走除外or中止
            else:
                elm = etr2.split(" ")[2] + " " + etr2.split(" ")[3] + " " + etr2.split(" ")[4] # exsample 2/3(中京) 芝2000  2.02.2 
            ls.append(elm)
        CourseTime.append(ls)

    NameCrsTime =[]
    for hrs in range(len(entries3_df)):
        NameCrsTime.append(HrsInfo[hrs] + CourseTime[hrs])

    #print(NameCrsTime[0])

    """ 1-4) 過去５走コーナー順位・人気 """
    CnrPopularityOdr=[]
    for h in range(len(entries3_df)):
        ls =[]
        for r in [8, 7, 6, 5, 4]:
            etr3 = str(re.sub("  "," ", str(entries3_df.iloc[[h], [r]].values[0][0])))
            if(etr3 == 'nan'):
                elm = ''
            elif(len(etr3.split(" ")) < 4):
                elm = "競走除外or中止"
            else:
                elm = etr3.split(" ")[5] + " " + etr3.split(" ")[6]
            ls.append(elm) # 
        CnrPopularityOdr.append(ls)

    NameCnrPopOdr =[]
    for h in range(len(entries3_df)):
        NameCnrPopOdr.append(HrsInfo[h] + CnrPopularityOdr[h])

    #print(NameCnrPopOdr[0])
    
    MyEntries =[]
    for h in range(len(entries2_df)):
        MyEntries.append(NameOdrTitle[h])
        MyEntries.append(NameCrsTime[h])
        MyEntries.append(NameWeiJockey[h])
        MyEntries.append(NameCnrPopOdr[h])

    set_df = pd.DataFrame(MyEntries, columns=['馬番', '馬名', 'S歳', '体重', '騎手', '斤量', '全成績', '重賞成績', '総賞金', '-', \
                                            '前走', '前々走', '3走前', '4走前', '5走前']) # index=idx_horse, 

    myEntries_df = set_df.set_index(['馬番','馬名', 'S歳', '体重', '騎手', '斤量', '全成績', '重賞成績', '総賞金', '-'])
    #myEntries_df.sort_index(level=0)
    return info_race, myEntries_df
    MyEntries =[]
    for h in mySortList:
        MyEntries.append(NameOdrTitle[h])
        MyEntries.append(NameCrsTime[h])
        MyEntries.append(NameWeiJockey[h])
        MyEntries.append(NameCnrPopOdr[h])

    set_df = pd.DataFrame(MyEntries, columns=['馬番', '馬名', 'S歳', '体重', '騎手', '斤量', '全成績','重賞成績', '総賞金', \
                                              '-', '前走', '前々走', '3走前', '4走前', '5走前']) # index=idx_horse, 

    myEntries_df = set_df.set_index(['馬番','馬名', 'S歳', '体重', '騎手', '斤量', '全成績', '重賞成績', '総賞金', '-'])
    #myEntries_df.sort_index(level=0)
    return myEntries_df

""" 人気・血統・コメント """
def myPopularityDF( race_code):
    """ オッズ """
    odds_url="https://race.netkeiba.com/?pid=race_old&id=c2019" + race_code
    sleep(1)
    od_df=pd.io.html.read_html(odds_url)

    od_df[0].columns = od_df[0].columns.droplevel() # 2重のカラム名 MultiIndex の1行削除
    odds_df = od_df[0].drop("馬体重", axis=1)

    """ 調教師コメント """
    train_url="https://race.netkeiba.com/?pid=race_old&id=c2019" + race_code + "&mode=oikiri"
    sleep(1)
    cmt_df=pd.io.html.read_html(train_url)
    cdf = cmt_df[0]
    comment_df = pd.concat([DataFrame(cdf['評価.1']), DataFrame(cdf['評価'])], axis=1)

    """ 血統 ( from 出馬表1) """
    entries1_html = urllib.request.urlopen("https://keiba.yahoo.co.jp/race/denma/19" + race_code + "/?page=1")
    entries1_soup = BeautifulSoup(entries1_html,"lxml")
    df1 = pd.io.html.read_html(entries1_soup.prettify())
    entries1_df = df1[2]
    
    blood = []
    for hrs in range(len(entries1_df)):
        bld = str(entries1_df.iloc[[hrs], [5]].values[0][0]).replace("  ", "/")
        bld = bld.replace("/(", "(")
        blood.append(bld)

    blood_df = pd.DataFrame(blood, columns=['血統'])
    #print(blood_df)
    popularity_df = pd.concat([odds_df, blood_df, comment_df], axis=1)
    
    return popularity_df

print("code loading ", datetime.now().strftime("%Y/%m/%d %H:%M:%S"))

code loading  2019/09/13 21:05:06

In [20]:
#race_code = rc["阪神sat"] + "03"
race_code = rc["中山sun"] + "09"
race_meta, race_df = myEntriesDF(race_code)
print(race_meta[:5], '\n', race_meta[5:11])
display(race_df)

['2019年9月15日（日）', '4回中山4日', '9R', '汐留特別', '14:35発走']
 ['芝・右2000m', '天気：晴', '馬場：良', 'サラ系3歳以上', '1勝クラス(500万下)指定定量', '本賞金：1050、420、260、160、105万円']

                                                                                 前走  \
馬番 馬名        S歳  体重     騎手     斤量   全成績      重賞成績    総賞金   -
01 マイネルエキサイト 牡3  -( - ) 柴田 大知  54.0 1.1.0.7  0.0.0.0 780万              09着 山藤賞(500)
                                                              4/13(中山) 芝1800 1.49.8
                                                                  472(-6) 柴田大知 (56)
                                                                   35.7 01-01-01-01
02 フィデリオグリーン 牡3  -( - ) 野中 悠太郎 54.0 1.0.2.5  0.0.0.1 1019万           03着 雄国沼(1勝クラス)
                                                              7/13(福島) 芝1800 1.48.5
                                                                 494(-4) 野中悠太郎 (54)
                                                                   34.3 08-08-08-09
03 ブラッドストーン  牡3  -( - ) 吉田 豊   54.0 1.1.2.2  0.0.0.0 1252万           03着 3歳上(1勝クラス)
                                                              6/29(福島) 芝2600 2.40.6
                                                                   474(+2) 吉田豊 (53)
                                                                   36.9 02-02-02-02
04 ウィナーポイント  牝4  -( - ) 横山 典弘  55.0 1.0.4.10 0.0.0.0 1450万           03着 糸魚川(1勝クラス)
                                                              8/31(新潟) 芝2000 2.00.0
                                                                  418(+4) 田辺裕信 (55)
                                                                         34.3 11-11
05 ウォルフズハウル  牡3  -( - ) 石橋 脩   54.0 1.1.0.1  0.0.0.0 700万                   01着 未勝利
                                                               7/7(福島) 芝2000 2.03.1
                                                                   462(+6) 石橋脩 (56)
                                                                   36.5 01-01-01-01
06 ナミブ       牡3  -( - ) 松岡 正海  54.0 1.0.2.17 0.0.0.0 1010万           07着 3歳上(1勝クラス)
                                                              8/31(札幌) 芝2000 2.04.3
                                                                 452(+12) 松岡正海 (54)
                                                                   37.6 07-07-07-09
07 ダイシンクイント  牡5  -( - ) 田中 勝春  57.0 1.1.2.18 0.0.0.0 1818万           05着 糸魚川(1勝クラス)
                                                              8/31(新潟) 芝2000 2.00.1
                                                                 474(-10) 田中勝春 (57)
                                                                         36.6 02-02
08 ツクバソヴァール  牡3  -( - ) 大野 拓弥  54.0 1.0.4.8  0.0.0.0 1512万           03着 3歳上(1勝クラス)
                                                              6/23(東京) 芝2000 2.00.5
                                                                 470(+10) 松岡正海 (54)
                                                                      36.2 04-04-05
09 クリノオスマン   せん5 -( - ) 宮崎 北斗  57.0 0.1.2.8  0.0.0.0 996万            02着 糸魚川(1勝クラス)
                                                              8/31(新潟) 芝2000 1.59.8
                                                                   450(0) 宮崎北斗 (57)
                                                                         34.5 05-04

                                                                                前々走  \
馬番 馬名        S歳  体重     騎手     斤量   全成績      重賞成績    総賞金   -
01 マイネルエキサイト 牡3  -( - ) 柴田 大知  54.0 1.1.0.7  0.0.0.0 780万               06着 3歳(500)
                                                              3/10(中山) 芝2000 2.02.5
                                                                  478(+2) 柴田大知 (56)
                                                                   37.1 01-02-02-02
02 フィデリオグリーン 牡3  -( - ) 野中 悠太郎 54.0 1.0.2.5  0.0.0.1 1019万             12着 スプS(GII)
                                                              3/17(中山) 芝1800 1.48.8
                                                                 498(-4) 野中悠太郎 (56)
                                                                   35.8 08-08-08-08
03 ブラッドストーン  牡3  -( - ) 吉田 豊   54.0 1.1.2.2  0.0.0.0 1252万             03着 夏木立(500)
                                                              5/11(東京) 芝2000 1.59.7
                                                                   472(+6) 吉田豊 (56)
                                                                      34.3 01-01-01
04 ウィナーポイント  牝4  -( - ) 横山 典弘  55.0 1.0.4.10 0.0.0.0 1450万           03着 3歳上(1勝クラス)
                                                              7/20(福島) 芝1800 1.49.5
                                                                  414(-2) 横山典弘 (55)
                                                                   35.6 13-12-12-09
05 ウォルフズハウル  牡3  -( - ) 石橋 脩   54.0 1.1.0.1  0.0.0.0 700万                   02着 未勝利
                                                              3/24(中山) 芝2200 2.15.6
                                                                   456(0) 藤岡佑介 (56)
                                                                   37.1 02-02-02-02
06 ナミブ       牡3  -( - ) 松岡 正海  54.0 1.0.2.17 0.0.0.0 1010万                  01着 未勝利
                                                               8/3(札幌) 芝2000 2.02.8
                                                                  440(-2) 菅原明良 (53)
                                                                   35.9 06-06-09-04
07 ダイシンクイント  牡5  -( - ) 田中 勝春  57.0 1.1.2.18 0.0.0.0 1818万           09着 御在所(1勝クラス)
                                                              6/29(中京) 芝1600 1.35.1
                                                                   484(-6) 幸英明 (57)
                                                                      35.5 02-02-02
08 ツクバソヴァール  牡3  -( - ) 大野 拓弥  54.0 1.0.4.8  0.0.0.0 1512万           xx着 稲城特(1勝クラス)
                                                                     6/15(東京) 芝2400
                                                                               大野拓弥
                                                                           競走除外or中止
09 クリノオスマン   せん5 -( - ) 宮崎 北斗  57.0 0.1.2.8  0.0.0.0 996万            06着 国分寺(1勝クラス)
                                                               6/1(東京) 芝1800 1.46.5
                                                                  450(-4) 嶋田純次 (57)
                                                                      33.9 08-09-07

                                                                                3走前  \
馬番 馬名        S歳  体重     騎手     斤量   全成績      重賞成績    総賞金   -
01 マイネルエキサイト 牡3  -( - ) 柴田 大知  54.0 1.1.0.7  0.0.0.0 780万              08着 フリー(500)
                                                              2/16(東京) 芝2000 2.01.5
                                                                  476(-4) 柴田大知 (56)
                                                                      35.6 01-01-01
02 フィデリオグリーン 牡3  -( - ) 野中 悠太郎 54.0 1.0.2.5  0.0.0.1 1019万             09着 水仙賞(500)
                                                              2/23(中山) 芝2200 2.14.3
                                                                 502(-2) 野中悠太郎 (56)
                                                                   38.0 04-05-05-08
03 ブラッドストーン  牡3  -( - ) 吉田 豊   54.0 1.1.2.2  0.0.0.0 1252万                  01着 未勝利
                                                              4/14(中山) 芝2200 2.14.2
                                                                     466(0) 武豊 (56)
                                                                   35.5 01-01-01-01
04 ウィナーポイント  牝4  -( - ) 横山 典弘  55.0 1.0.4.10 0.0.0.0 1450万           04着 織姫賞(1勝クラス)
                                                               7/7(福島) 芝1800 1.48.6
                                                                  416(-8) 大野拓弥 (55)
                                                                   35.9 13-12-12-08
05 ウォルフズハウル  牡3  -( - ) 石橋 脩   54.0 1.1.0.1  0.0.0.0 700万                    07着 新馬
                                                              2/11(東京) 芝1600 1.36.8
                                                                   456(-) 大野拓弥 (56)
                                                                         34.4 14-14
06 ナミブ       牡3  -( - ) 松岡 正海  54.0 1.0.2.17 0.0.0.0 1010万                  03着 未勝利
                                                              7/14(函館) 芝2000 2.03.4
                                                                  442(+4) 菅原明良 (53)
                                                                   35.9 06-06-05-04
07 ダイシンクイント  牡5  -( - ) 田中 勝春  57.0 1.1.2.18 0.0.0.0 1818万             03着 春日山(500)
                                                              4/27(新潟) 芝2000 2.01.8
                                                                  482(-2) 岩田康誠 (57)
                                                                         36.3 01-01
08 ツクバソヴァール  牡3  -( - ) 大野 拓弥  54.0 1.0.4.8  0.0.0.0 1512万              04着 3歳(500)
                                                              5/25(東京) 芝2400 2.26.1
                                                                  460(-4) 大野拓弥 (56)
                                                                   34.2 03-03-03-03
09 クリノオスマン   せん5 -( - ) 宮崎 北斗  57.0 0.1.2.8  0.0.0.0 996万              03着 二王子(500)
                                                               5/5(新潟) 芝1800 1.47.4
                                                                  454(-4) 嶋田純次 (57)
                                                                         33.2 09-11

                                                                                4走前  \
馬番 馬名        S歳  体重     騎手     斤量   全成績      重賞成績    総賞金   -
01 マイネルエキサイト 牡3  -( - ) 柴田 大知  54.0 1.1.0.7  0.0.0.0 780万              06着 セント(500)
                                                              1/27(東京) 芝1800 1.49.5
                                                                  480(+2) 柴田大知 (56)
                                                                      35.0 01-01-01
02 フィデリオグリーン 牡3  -( - ) 野中 悠太郎 54.0 1.0.2.5  0.0.0.1 1019万                  01着 未勝利
                                                              2/10(小倉) 芝2000 2.03.2
                                                                   504(0) 丸山元気 (56)
                                                                   37.3 01-01-01-01
03 ブラッドストーン  牡3  -( - ) 吉田 豊   54.0 1.1.2.2  0.0.0.0 1252万                  02着 未勝利
                                                              3/23(中山) 芝1800 1.50.7
                                                                    466(-6) 武豊 (56)
                                                                   36.0 04-05-01-01
04 ウィナーポイント  牝4  -( - ) 横山 典弘  55.0 1.0.4.10 0.0.0.0 1450万           07着 3歳上(1勝クラス)
                                                              6/23(東京) 芝1800 1.48.5
                                                                424(+26) 野中悠太郎 (53)
                                                                      34.3 04-05-04
05 ウォルフズハウル  牡3  -( - ) 石橋 脩   54.0 1.1.0.1  0.0.0.0 700万



06 ナミブ       牡3  -( - ) 松岡 正海  54.0 1.0.2.17 0.0.0.0 1010万                  04着 未勝利
                                                              6/23(函館) 芝2000 2.03.1
                                                                  438(+2) 菅原明良 (53)
                                                                   37.1 02-02-02-02
07 ダイシンクイント  牡5  -( - ) 田中 勝春  57.0 1.1.2.18 0.0.0.0 1818万             xx着 4歳上(500)
                                                                     3/30(阪神) 芝2000
                                                                                荻野極
                                                                           競走除外or中止
08 ツクバソヴァール  牡3  -( - ) 大野 拓弥  54.0 1.0.4.8  0.0.0.0 1512万             03着 新緑賞(500)
                                                              4/20(東京) 芝2300 2.20.3
                                                                  464(-4) 大野拓弥 (56)
                                                                   35.2 04-04-05-05
09 クリノオスマン   せん5 -( - ) 宮崎 北斗  57.0 0.1.2.8  0.0.0.0 996万              03着 4歳上(500)
                                                              4/21(東京) 芝2000 2.01.6
                                                                  458(-2) 嶋田純次 (57)
                                                                      33.3 05-06-07

                                                                                5走前
馬番 馬名        S歳  体重     騎手     斤量   全成績      重賞成績    総賞金   -
01 マイネルエキサイト 牡3  -( - ) 柴田 大知  54.0 1.1.0.7  0.0.0.0 780万               10着 3歳(500)
                                                               1/5(中山) 芝2000 2.03.3
                                                                  478(+8) 柴田大知 (56)
                                                                   35.2 08-08-08-08
02 フィデリオグリーン 牡3  -( - ) 野中 悠太郎 54.0 1.0.2.5  0.0.0.1 1019万                  04着 未勝利
                                                              1/19(中山) ダ1800 1.59.2
                                                                 504(+4) 野中悠太郎 (53)
                                                                   41.9 04-06-04-04
03 ブラッドストーン  牡3  -( - ) 吉田 豊   54.0 1.1.2.2  0.0.0.0 1252万                  05着 未勝利
                                                              2/23(中山) 芝1800 1.48.3
                                                                  472(+2) 木幡育也 (53)
                                                                   36.0 02-02-03-03
04 ウィナーポイント  牝4  -( - ) 横山 典弘  55.0 1.0.4.10 0.0.0.0 1450万             06着 脊振山(500)
                                                              2/24(小倉) 芝1800 1.48.6
                                                                 398(-4) 藤田菜七子 (54)
                                                                   36.1 03-05-07-08
05 ウォルフズハウル  牡3  -( - ) 石橋 脩   54.0 1.1.0.1  0.0.0.0 700万



06 ナミブ       牡3  -( - ) 松岡 正海  54.0 1.0.2.17 0.0.0.0 1010万                  10着 未勝利
                                                              6/15(函館) 芝2000 2.01.3
                                                                 436(-12) 松岡正海 (56)
                                                                   37.1 03-03-03-04
07 ダイシンクイント  牡5  -( - ) 田中 勝春  57.0 1.1.2.18 0.0.0.0 1818万             10着 長良川(500)
                                                              12/9(中京) 芝2200 2.15.2
                                                                   486(+8) 小牧太 (57)
                                                                   36.3 05-05-05-03
08 ツクバソヴァール  牡3  -( - ) 大野 拓弥  54.0 1.0.4.8  0.0.0.0 1512万             06着 山吹賞(500)
                                                              3/30(中山) 芝2200 2.15.3
                                                                  468(-4) 丹内祐次 (56)
                                                                   35.4 03-03-04-07
09 クリノオスマン   せん5 -( - ) 宮崎 北斗  57.0 0.1.2.8  0.0.0.0 996万              10着 4歳上(500)
                                                              3/31(中山) ダ1800 1.57.5
                                                                  460(+8) 菊沢一樹 (55)
                                                                   40.4 07-07-07-08

In [21]:
""" 人気情報(単オッズ) """
PopularityDF = myPopularityDF( race_code)
print(race_meta[:6])
PopularityDF.sort_values(by='人気')

['2019年9月15日（日）', '4回中山4日', '9R', '汐留特別', '14:35発走', '芝・右2000m']

,枠番,馬番,馬名,性齢,負担重量,騎手,厩舎,単勝オッズ,人気,血統,評価.1,評価
2,3,3,ブラッドストーン,牡3,54.0,吉田豊,小島,3.3,1,ローズキングダム/マレンカヤ(ファンタスティックライト),C,仕上十分
4,5,5,ウォルフズハウル,牡3,54.0,石橋脩,栗田,3.8,2,ハーツクライ/アークティックシルク(Selkirk),B,伸び上々
3,4,4,ウィナーポイント,牝4,55.0,横山典,和田勇,5.9,3,スクリーンヒーロー/メイクデュース(トウカイテイオー),B,状態良好
6,7,7,ダイシンクイント,牡5,57.0,田中勝,森,8.6,4,ルーラーシップ/ダイシンキャンディ(アグネスタキオン),B,叩き良化
8,8,9,クリノオスマン,セ5,57.0,宮崎,伊藤伸,8.7,5,ナカヤマフェスタ/ダービーゾーン(サニーブライアン),C,先着平凡
7,8,8,ツクバソヴァール,牡3,54.0,大野,杉浦,8.9,6,ロジユニヴァース/リリーオブザナイル(バゴ),C,前走並み
1,2,2,フィデリオグリーン,牡3,54.0,野中,根本,11.3,7,ザサンデーフサイチ/ミサノグリーン(タニノギムレット),C,まずまず
0,1,1,マイネルエキサイト,牡3,54.0,柴田大,加藤士,20.6,8,ブラックタイド/アインライツ(ティンバーカントリー),C,遅れ上々
5,6,6,ナミブ,牡3,54.0,松岡,南田,22.0,9,ナカヤマフェスタ/マイネジャンヌ(ロージズインメイ),B,動き良化

In [93]:
""" 結果 """
result_html =  "https://keiba.yahoo.co.jp/race/result/19" + race_code + "/"
ResultDF = pd.io.html.read_html(result_html)
print(race_meta[:5])
ResultDF[4]

['2019年8月25日（日）', '2回札幌4日', '11R', 'キーンランドカップ（GIII）', '15:35発走']

,着順,枠番,馬番,馬名性齢⁄馬体重⁄B,タイム(着差),通過順位上3Fタイム,騎手,人気(オッズ),調教師
0,1,7,13,ダノンスマッシュ 牡4/478(+6)/,1.09.2,07-0635.3,川田 将雅 57.0,1 (2.3),安田 隆行
1,2,4,7,タワーオブロンドン 牡4/520(+2)/,1.09.33/4馬身,12-1234.9,C.ルメール 58.0,2 (4.7),藤沢 和雄
2,3,8,16,リナーテ 牝5/488(-8)/,1.09.3ハナ,08-0835.2,武 豊 54.0,3 (6.6),須貝 尚介
3,4,7,14,ライトオンキュー 牡4/514(-2)/,1.09.4クビ,12-1135.1,古川 吉洋 56.0,11 (42.5),昆 貢
4,5,1,1,ナックビーナス 牝6/526(+3)/,1.09.61 1/2馬身,01-0136.4,岩田 康誠 55.0,4 (12.6),杉浦 宏昭
5,6,2,4,セイウンコウセイ 牡6/502(-4)/,1.09.73/4馬身,03-0436.3,幸 英明 58.0,5 (13.8),上原 博之
6,7,3,5,ペイシャフェリシタ 牝6/494(0)/,1.09.8クビ,04-0236.2,K.ティータン 54.0,13 (63.1),高木 登
7,8,1,2,デアレガーロ 牝5/482(+2)/,1.09.8クビ,08-0835.7,池添 謙一 54.0,6 (15.6),大竹 正博
8,9,8,15,パラダイスガーデン 牝7/502(+4)/,1.09.91/2馬身,16-1634.9,横山 武史 54.0,15 (223.9),粕谷 昌央
9,10,3,6,ハッピーアワー 牡3/446(+4)/,1.10.03/4馬身,15-1435.4,吉田 隼人 54.0,8 (21.1),武 幸四郎
10,11,6,11,ライオンボス 牡4/528(-10)/,1.10.21 1/4馬身,02-0237.0,J.ルパルー 57.0,9 (23.1),和田 正一郎
11,12,5,9,カイザーメランジェ 牡4/462(-12)/,1.10.31/2馬身,06-0636.5,江田 照男 57.0,10 (39),中野 栄治
12,13,4,8,シュウジ 牡6/506(-4)/,1.10.93 1/2馬身,08-0836.8,三浦 皇成 57.0,14 (80.3),須貝 尚介
13,14,6,12,ダイメイフジ 牡5/524(0)/,1.11.0クビ,04-0537.4,L.オールプレス 56.0,12 (55.9),森田 直行
14,15,2,3,サフランハート 牡6/464(+8)/,1.11.32馬身,12-1236.9,勝浦 正樹 56.0,16 (479.1),北出 成人
15,16,5,10,アスターペガサス 牡3/512(+18)/,1.12.25馬身,11-1438.0,戸崎 圭太 53.0,7 (16.5),中竹 和也

In [92]:
""" 払い戻し """
print(race_meta[:5])
tst_df = pd.concat([ResultDF[2], ResultDF[3]])
tst_df.reset_index(drop=True)

['2019年8月25日（日）', '2回札幌4日', '11R', 'キーンランドカップ（GIII）', '15:35発走']

      0        1       2     3
0    単勝       13    230円  1番人気
1    複勝       13    110円  1番人気
2    複勝        7    150円  2番人気
3    複勝       16    180円  3番人気
4    枠連      4－7    640円  1番人気
5    馬連     7－13    760円  1番人気
6   ワイド     7－13    300円  1番人気
7   ワイド     7－16    640円  5番人気
8   ワイド    13－16    330円  2番人気
9    馬単     13－7  1,170円  1番人気
10  3連複  7－13－16  1,410円  1番人気
11  3連単  13－7－16  4,480円  1番人気

In [5]:
""" my出馬表の人気順・結果順 """
pS_ls = [PopularityDF.sort_values(by='人気').iloc[[h],[1]].values.tolist() for h in range(len(entries1_df))]
popSort = [pS_ls[h][0][0] for h in range(len(entries1_df))]
PopulartySort = [ h - 1 for h in popSort]

""" my出馬表の結果順 """
rS_ls = [ResultDF[4].iloc[[h],[2]].values.tolist() for h in range(len(entries1_df))]
rltSort = [rS_ls[h][0][0] for h in range(len(entries1_df))]
ResultSort = [ h - 1 for h in rltSort]

print(re.sub(r"[\[',\]]","", str(info_basic)), " ", str(info_meta[0]), str(info_meta[1]), str(info_meta[2]))
# myEntriesDF(PopulartySort)
myEntriesDF(ResultSort)

NameError: name 'entries1_df' is not defined

In [333]:
url="https://race.netkeiba.com/?pid=race_old&id=c201901020301"
print(url)

https://race.netkeiba.com/?pid=race_old&id=c201901020301

In [223]:
for s in crs_dic.keys():
    if(s[2:]=='sat'): w = '(土)'
    else: w = '(日)'
    print(s[:2], w)
    print(crs_dic[s])

札幌 (土)
010205
新潟 (土)
040211
小倉 (土)
100211
札幌 (日)
010206
新潟 (日)
040212
小倉 (日)
100212

In [3]:
import unicodedata
def left(digit, msg):
    for c in msg:
        if unicodedata.east_asian_width(c) in ('F', 'W', 'A'):
            digit -= 2
        else:
            digit -= 1
    return msg + ' '*digit

""" 掲示板内の結果 """
rc = {}
rc['札幌sat'] = '010205' #8/31
rc['新潟sat'] = '040211'
rc['小倉sat'] = '100211'
rc['札幌sun'] = '010206' #9/1
rc['新潟sun'] = '040212'
rc['小倉sun'] = '100212'

for v in rc.values():
    for r in range(12):
        result_html =  "https://keiba.yahoo.co.jp/race/result/19" + str(v) + str(r+1).rjust(2,"0")
        sleep(1)
        ResultDF = pd.io.html.read_html(result_html)
        nnR = ResultDF[1].iloc[[0]].values[0][0]
        rcode = ResultDF[1].iloc[[0]].values[0][1].split(" | ")[1]
        rtitle = ResultDF[1].iloc[[0]].values[0][1].split(" | ")[2]
        print(rcode, nnR, rtitle)
        """ レース結果 """
        for i in range(8):
            rslt = ResultDF[4].iloc[[i]]
            odr = str(rslt.iloc[[0], [2]].values[0][0])
            hrs = str(rslt.iloc[[0], [3]].values[0][0]).split("  ")[0]
            pop = rslt.iloc[[0], [7]].values[0][0]
            print("{:} {:} {:}".format( odr.rjust(2), left(25, hrs) , pop))

2回札幌5日 1R 9:50発走 サラ系2歳未勝利 芝・右 2000m
 2 ミヤマザクラ              2 (2.6)
14 ナスノフォルテ            9 (135)
 9 メリディアンローグ        1 (1.9)
10 アベルゴー                10 (225.5)
 3 エピファレーヌ            3 (11)
13 アピテソーロ              5 (25.7)
 8 シャーベットフィズ        16 (605.5)
 7 サイモンルグラン          8 (99.8)
2回札幌5日 2R 10:25発走 サラ系2歳未勝利 ダート・右 1700m
12 デルマオニキス            9 (39.9)
 7 クレパト                  3 (11.1)
 2 バカラ                    1 (1.3)
14 ディーエスプルーフ        6 (25.2)
 6 ウインアクティーボ        2 (8)
 1 ヤマノマタカ              5 (20.1)
 5 ラフリッグフェル          4 (17.1)
 9 ワンダーカムラング        8 (39.7)
2回札幌5日 3R 10:55発走 サラ系3歳未勝利 ダート・右 1000m
12 ファロ                    2 (3.8)
11 テイエムダイリン          4 (6.2)
 4 グランデオーロラ          3 (6.2)
 3 モエレコネクター          8 (22.2)
 1 エルマスフエルテ          9 (27.5)
 9 ビービーアライヴ          1 (3)
10 タカラチーター            11 (115.2)
 5 ローマノキュウジツ        7 (20)
2回札幌5日 4R 11:25発走 サラ系3歳未勝利 芝・右 1200m
 6 レッドクレオス            1 (1.9)
15 ドゥシャンパーニュ        4 (12.5)
10 ソルパシオン              5 (12.7)
16 マイネルカゲツ            10 (27.2)
12 フェニアンサイクル        7 (13.9)
 9 ボナセーラ                2 (8.3)
 7 マカリカ                  3 (10.9)
11 マルニ                    6 (13.7)
2回札幌5日 5R 12:15発走 サラ系2歳新馬 芝・右 1500m
11 アイスシェルフ            5 (8.7)
10 テイストオブハニー        4 (8.3)
 6 ミネルバ                  2 (6.6)
13 デルマトパーズ            10 (117.1)
 1 オーロラフラッシュ        3 (6.8)
12 ダノンオスカル            6 (11.1)
 8 アースレイナ              12 (246.1)
 2 ピエナファリア            7 (36.4)
2回札幌5日 6R 12:45発走 サラ系3歳未勝利 ダート・右 1700m
 2 マーベラスアゲン          9 (24.5)
 7 サンドル                  3 (4.8)
 1 マーブルサニー            4 (10.5)
 6 ヤークトボマー            1 (2.7)
12 ジューンハルジオン        2 (3.9)
11 チェンマイルージュ        10 (25.3)
 4 トライゲッター            5 (17.6)
14 マレキアーレ              6 (18.2)
2回札幌5日 7R 13:15発走 サラ系3歳上1勝クラス(500万円以下) ダート・右 1700m
 3 タイトロープウィン        1 (1.9)
 9 ショウナンマシェリ        4 (8.6)
14 カグラヒメ                2 (4.6)
 4 ゴーインピース            3 (5.3)
 5 ドヒョウギワ              8 (31.6)
 6 フクキタル                9 (33.1)
10 ラヴノット                11 (69.9)
 2 クリノイヴァンカ          6 (26)
2回札幌5日 8R 13:45発走 サラ系3歳上1勝クラス(500万円以下) 芝・右 2000m
 4 ブラヴァス                2 (3)
 3 アリスブルー              4 (8.3)
 7 ワセダインブルー          1 (2.8)
11 ウインラナキラ            3 (3.8)
16 ウインプライマリー        10 (74.1)
12 メガディスカバリー        12 (136.9)
 9 ナミブ                    6 (22.7)
 2 ジン                      11 (119.2)
2回札幌5日 9R 14:15発走 サラ系3歳上1勝クラス(500万円以下) ダート・右 1700m
10 ペプチドバンブー          1 (3.4)
12 ブロッコリー              2 (3.5)
13 ヒラソール                3 (4.8)
 7 クリノカポネ              9 (25.3)
 9 オウケンスターダム        8 (22.6)
 2 サミットプッシュ          5 (10.3)
14 チェルシーライオン        11 (63)
 3 サンレイファイト          6 (15.2)
2回札幌5日 10R 14:50発走 札幌スポニチ賞 芝・右 1200m
 3 スリーケープマンボ        12 (46.8)
10 フォレブルート            1 (2.3)
11 ショウナンアリアナ        6 (16.7)
 2 ヤマニンペダラーダ        2 (5.5)
 1 デルタバローズ            4 (8.9)
15 プレトリア                7 (21.7)
13 オフクヒメ                9 (24.5)
 8 シンデレラメイク          5 (14.4)
2回札幌5日 11R 15:25発走 第54回札幌2歳ステークス（GIII） 芝・右 1800m
 6 ブラックホール            5 (29.4)
11 サトノゴールド            3 (10.2)
 1 ダーリントンホール        2 (2.8)
 5 レザネフォール            4 (20)
 4 ヨハネスボーイ            7 (44.4)
10 ゴルコンダ                1 (1.8)
 3 コンドゥクシオン          9 (71)
 9 ディアセオリー            6 (38.2)
2回札幌5日 12R 16:05発走 日高特別 芝・右 2000m
 1 ハウエバー                8 (23.5)
 7 サンシロウ                2 (4)
10 クラサーヴィツァ          7 (16.8)
 4 トーセンスーリヤ          4 (9)
11 ムーンライトナイト        6 (13.8)
16 シュバルツボンバー        13 (74.4)
 8 メイショウテンシャ        12 (68.1)
 2 スワーヴノートン          11 (29.2)
2回新潟11日 1R 10:10発走 サラ系2歳未勝利 芝・左・外 1600m
12 マルターズディオサ        1 (2.7)
17 マイネルシスネロス        5 (17.6)
11 ハーモニーマゼラン        4 (6.8)
14 タイキスウォード          7 (31.8)
 5 コウソクスピード          2 (3.5)
 4 サンダーブリッツ          6 (29.1)
16 ヒューズライン            14 (323.8)
10 キララ                    12 (200.1)
2回新潟11日 2R 10:45発走 サラ系2歳未勝利 ダート・左 1800m
 5 マイネルアストリア        4 (12.6)
 7 クロカドッグ              13 (276.5)
 9 コスモケルビン            7 (43.4)
13 シゲルミカヅキ            1 (1.7)
 1 マイネルティプトン        11 (185.3)
 8 ノーブルミラクル          3 (7.3)
 6 フォンテーヌ              9 (78.7)
 2 グロワールポン            5 (24.5)
2回新潟11日 3R 11:15発走 サラ系3歳未勝利 芝・左 2000m
14 サトノセシル              1 (2.6)
11 ホウオウビクトリー        4 (8)
 8 ヤギリオーディン          10 (37.7)
 5 カフェシュヴァルツ        9 (26.7)
17 ブライティアセルバ        6 (12.2)
12 ココリアッピア            8 (19.7)
10 フェリスナタール          2 (5.4)
16 ニシノプレジール          7 (15.4)
2回新潟11日 4R 11:45発走 サラ系3歳未勝利 ダート・左 1800m
 9 トーホウボッカ            8 (17.4)
13 スカテナート              3 (6.1)
 4 ツキノサバク              9 (26.9)
 8 コットンスノー            1 (3.6)
 2 アッシュドール            4 (6.1)
14 シンティラ                2 (4)
 7 サイファリス              7 (15.6)
 6 バイプレーヤー            6 (14)
2回新潟11日 5R 12:35発走 サラ系2歳新馬 芝・左・外 1800m
 8 ミッキーメテオ            2 (3.1)
11 バルバレスコ              4 (13.9)
 5 シンドラー                5 (17.8)
 6 チュウワジョーダン        9 (68.6)
 9 キャルブルー              6 (40.8)
 7 ペルラネーラ              1 (1.7)
14 マイネルミンドール        3 (13.7)
13 マイネルシエル            11 (116.5)
2回新潟11日 6R 13:05発走 サラ系2歳新馬 ダート・左 1200m
 9 ラブオナヴィータ          3 (5.9)
 3 トーアリュウジン          7 (17.9)
11 コトブキレイア            6 (17.1)
 8 クワトロチェント          4 (8.5)
 1 エスニックソング          8 (30.9)
13 エイシンバッカス          1 (2.3)
 6 シバノレイワ              11 (144.5)
12 クリノファイヤー          12 (178.9)
2回新潟11日 7R 13:35発走 サラ系3歳未勝利 芝・直線 1000m
14 トモジャファイブ          1 (2.2)
16 カフェドラペ              3 (7.6)
17 ホシノウチカケ            6 (10.6)
 4 ウインドシャルム          14 (89.8)
 5 タイセイブランシュ        9 (34.5)
12 ヒートミープリーズ        5 (10.4)
 9 マロンクルール            15 (104.2)
 7 テミス                    4 (10)
2回新潟11日 8R 14:05発走 サラ系3歳上1勝クラス(500万円以下) ダート・左 1800m
11 レイナデルビエント        8 (47.8)
10 エンドーツダ              1 (2.7)
13 アポロプリンセス          3 (5.8)
 7 ボンドロール              7 (18.2)
 5 グログラン                4 (7.9)
 1 タツオウカランブ          5 (14.7)
 9 クラウンロマン            6 (15.9)
 6 ラブサンキュー            10 (82.4)
2回新潟11日 9R 14:37発走 糸魚川特別 芝・左・外 2000m
11 パルティアーモ            2 (6.3)
12 クリノオスマン            7 (28)
 1 ウィナーポイント          6 (12.1)
 7 ドリームインパクト        1 (2.1)
14 ダイシンクイント          8 (38.7)
 6 マジックリアリズム        3 (6.8)
 5 ラレゾン                  5 (7.5)
 3 シュテルンシチー          11 (167.2)
2回新潟11日 10R 15:11発走 飯豊特別 芝・左 1200m
18 ナランフレグ              1 (4.1)
 6 セイウンリリシイ          7 (18.3)
15 ファンタジステラ          4 (7.8)
 3 メジャーレート            5 (12.3)
 4 ダノンハイパワー          12 (41.3)
17 アーヒラ                  11 (37.7)
 7 メイラヴェル              3 (4.6)
14 ピースユニヴァース        6 (14.3)
2回新潟11日 11R 15:45発走 長岡ステークス 芝・左・外 1600m
 9 ロードマイウェイ          4 (7.4)
 4 アガラス                  5 (8.5)
 7 アントリューズ            1 (2.7)
 6 ミッキーブリランテ        2 (4.2)
 3 アバルラータ              9 (52.6)
 5 デスティニーソング        11 (94.7)
 2 ミスティックグロウ        6 (10.5)
10 レジーナドーロ            3 (6.5)
2回新潟11日 12R 16:30発走 サラ系3歳上1勝クラス(500万円以下) ダート・左 1200m
 1 オールデン                5 (7.4)
 7 ハナブショウ              8 (21.6)
 9 ラブユーミー              6 (13)
 4 グラデュエイト            3 (6.2)
 2 サリーバランセ            4 (6.3)
 3 ホマレ                    2 (5.8)
11 ホーカスポーカス          1 (2.5)
13 アドマイヤムテキ          7 (21)
2回小倉11日 1R 10:01発走 サラ系障害3歳上オープン 障害・芝 2860m
10 アグリッパーバイオ        1 (1.5)
 3 シゲルサツマイモ          10 (40.2)
11 クリュティエ              5 (14.2)
 8 ヤマニンシルフ            4 (10.9)
 1 サウスオブボーダー        3 (10.8)
 9 シゲルスズキ              11 (96)
 2 カレンバッドボーイ        8 (33.1)
 7 マイネルレオーネ          9 (33.3)
2回小倉11日 2R 10:35発走 サラ系2歳未勝利 芝・右 2000m
 4 フルートフルデイズ        5 (13.9)
 8 アバンダンスシチー        2 (3.5)
 1 ウインローズブーケ        3 (8.9)
 9 エキスパート              4 (10.6)
 5 ロッキーサンダー          6 (54)
 7 シャルロワ                1 (1.7)
 3 ジョウショーカード        9 (186.7)
 6 テイエムマルジュウ        8 (186)
2回小倉11日 3R 11:05発走 サラ系3歳未勝利 ダート・右 1000m
10 ディーズファンシー        9 (34.2)
 9 トーホウフレーテ          3 (7.8)
14 クーファピーカブー        1 (2)
12 イニシエーター            4 (8.7)
 2 アンラッシュ              11 (61.3)
 8 スペースコロニー          2 (4.8)
 3 ガールズロック            5 (8.9)
 5 フラッパー                8 (28.4)
2回小倉11日 4R 11:35発走 サラ系3歳未勝利 芝・右 1200m
 4 パーティナシティ          1 (2.8)
15 ダンシングプリンス        3 (4.9)
 6 ラッキーバローズ          2 (2.8)
 5 バトルアグレッシブ        14 (135)
10 ハピネスブルーム          4 (10.5)
11 ブラボーフェスタ          7 (31.6)
 9 ケイティグレース          5 (22.2)
18 ジャングルキッド          9 (47.2)
2回小倉11日 5R 12:25発走 サラ系2歳新馬 芝・右 1200m
13 パドゥヴァルス            3 (3.8)
 1 ハクアイブラック          9 (53.8)
 9 ピエーナテーラー          4 (14.3)
 3 アルタグラシア            1 (2.9)
16 タナノフローラ            7 (35.3)
12 セイウンミレイア          11 (77.7)
 4 ナムラピアノ              13 (112.4)
 6 ベルティアラ              10 (75.7)

2回小倉11日 6R 12:55発走 サラ系3歳未勝利 ダート・右 1700m
10 アイタイ                  1 (3.3)
 2 サンライズアカシア        5 (8)
 3 スズノチェルシー          8 (23.3)
 1 メイショウミチノク        4 (7)
 4 フェブタイズ              10 (30.8)
16 オウケンシャトル          16 (368.4)
11 メルテール                7 (18.4)
 9 スーパーアロイ            2 (5.2)
2回小倉11日 7R 13:25発走 サラ系3歳未勝利 芝・右 2000m
 4 ルベリエ                  3 (6.5)
14 リッカローズ              5 (9.3)
18 ブルーエクセレンス        1 (3)
 6 レッドジェニファー        7 (21.4)
13 レッドレイル              6 (19.9)
 2 アドマイヤジョイ          9 (25.7)
 3 エバークリア              13 (50)
 9 スノーユニバンス          2 (4.9)
2回小倉11日 8R 13:55発走 サラ系3歳上1勝クラス(500万円以下) ダート・右 1000m
 7 ノボリレーヴ              1 (3.2)
 4 サイモンゼーレ            7 (12)
 3 アユツリオヤジ            6 (10.2)
 8 トーホウレジーナ          2 (4.6)
 9 シルバークレイン          11 (37.9)
 1 ブライトメジャー          9 (23.8)
10 レナータ                  10 (24.5)
12 アメリカンソレイユ        5 (8.8)
2回小倉11日 9R 14:25発走 八幡特別 芝・右 1200m
12 キャスパリーグ            2 (4.1)
15 ブルベアオーロ            4 (6.6)
 1 クーファディーヴァ        3 (5.6)
 9 メイショウナスカ          5 (16.9)
11 スキップ                  8 (33.2)
14 シトリカ                  15 (407.7)
 8 タイセイトレンディ        7 (21.6)
 6 トモジャクアルト          9 (35.3)
2回小倉11日 10R 15:01発走 玄海特別 芝・右 2000m
10 レオコックブルー          3 (7.4)
 9 ヒンドゥタイムズ          1 (1.5)
 5 ルナステラ                2 (4.8)
 1 ルックスマート            9 (60.4)
 8 ジョウショームード        5 (20.5)
 4 ウインルチル              4 (14.7)
 3 レッドストーリア          12 (130.4)
 2 サンライズローリエ        6 (26)
2回小倉11日 11R 15:35発走 北九州短距離ステークス 芝・右 1200m
 1 メイショウカズヒメ        9 (24.5)
 9 ブライティアレディ        4 (11.4)
 7 マッスルマサムネ          12 (42.3)
 8 ラルムドランジュ          3 (9.7)
12 コロラトゥーレ            6 (14.3)
 6 ダイシンバルカン          8 (15.5)
 5 タイセイブレーク          2 (4.7)
14 キラーコンテンツ          5 (13.1)
2回小倉11日 12R 16:15発走 サラ系3歳上1勝クラス(500万円以下) ダート・右 1700m
14 ゴールドパッキャオ        3 (5.1)
 6 ケイアイパープル          9 (32.2)
12 テイエムクロムシャ        1 (3.2)
11 シャイニーロック          5 (8)
13 キクノフェリックス        2 (4.9)
 1 モダスオペランディ        7 (20.2)
10 メイショウカンキ          10 (33.6)
16 セヴィルロアー            8 (20.7)
2回札幌6日 1R 9:50発走 サラ系2歳未勝利 芝・右 1500m
 4 ベッラヴォルタ            1 (2.7)
14 イッツアワターン          2 (3.6)
 7 ピンポンダッシュ          11 (121.2)
10 タガノキトピロ            8 (45.2)
 2 トーセンシュバリエ        10 (94.7)
 1 ウインヴェルメリオ        4 (9.7)
11 ソティラス                9 (76.6)
 3 グレイスフルダンス        3 (4.9)
2回札幌6日 2R 10:25発走 サラ系2歳未勝利 芝・右 1200m
 2 メイプルプレゼント        5 (18.3)
 1 フィロス                  10 (28)
 7 クインズラプソディ        8 (23.4)
 9 フランジヴェント          1 (1.7)
10 フィールフォーユー        6 (21.3)
15 ユーメイドリーム          9 (25.5)
 6 プロヴィデンス            2 (6.6)
11 サンライト                4 (13.4)
2回札幌6日 3R 10:55発走 サラ系3歳未勝利 ダート・右 1700m
 7 ビービーシャルト          6 (14)
 4 ハートウォーミング        1 (2.2)
11 オウケンランボー          7 (20.1)
 8 オーミシンゲン            11 (65.9)
10 モーンストルム            5 (10.4)
 5 ヘルムヴィーゲ            10 (54.7)
 1 シュンカジョウ            8 (24)
 9 ビッグバジェット          3 (9.2)
2回札幌6日 4R 11:25発走 サラ系3歳未勝利 芝・右 2000m
10 ホウオウエーデル          5 (9.6)
13 トゥールナージュ          8 (13.1)
11 シークレットアイズ        1 (3.9)
14 テンペスタージ            9 (23)
 4 クロスオブヴァロー        3 (6.8)
16 ロードアブソルート        12 (27.9)
12 バイキングクラップ        6 (10.4)
 2 メイプルランド            16 (187.7)
2回札幌6日 5R 12:15発走 サラ系3歳未勝利 ダート・右 1700m
 5 エスキシータ              8 (25.1)
 4 シゲルクロダイヤ          1 (2.8)
13 ゼットレオ                4 (10.4)
 9 ウォーターリベルテ        11 (49)
 6 エストレラブランコ        6 (17.9)
 3 カーブドシール            3 (4.9)
 1 サトノダイナスティ        2 (3.1)
14 バシクンレッツゴー        10 (47.9)
2回札幌6日 6R 12:45発走 サラ系3歳上1勝クラス(500万円以下) ダート・右 1000m
 6 ゴールデンチョイス        3 (5.5)
12 ヘルメット                8 (15.9)
11 メイショウメイリン        5 (8.8)
 2 ラブリースパイス          9 (17)
 5 オルダージュ              6 (11)
 1 ノボシュンシュン          1 (3.6)
 9 サノノショウグン          2 (4.3)
 3 セグレートシチー          10 (34.5)
2回札幌6日 7R 13:15発走 サラ系3歳上1勝クラス(500万円以下) 芝・右 1200m
16 イーサンパンサー          1 (3.7)
 9 スズカフェラリー          4 (8.2)
12 パラーティウム            2 (4.8)
 8 ニシノドレッシー          9 (18.2)
 7 ファンシャン              6 (12.6)
11 ヴィーナスフローラ        3 (8)
 5 コスモペリドット          8 (15.6)
14 ナンゴクアイネット        10 (27.7)
2回札幌6日 8R 13:45発走 サラ系3歳上1勝クラス(500万円以下) ダート・右 1700m
 3 ブラックカード            2 (5)
10 フクノワイルド            6 (10.9)
 1 マースゴールド            3 (5.4)
 7 キングスクロス            7 (12.9)
 8 バンクショット            8 (15.9)
 2 ナイルデルタ              4 (6.3)
 4 シンアンドケン            5 (8.9)
 5 テーオーポシブル          1 (3.6)
2回札幌6日 9R 14:15発走 サラ系3歳上1勝クラス(500万円以下) 芝・右 1800m
 8 クリノアリエル            2 (4.5)
 6 タンタグローリア          4 (6.3)
12 マイネルザウバア          5 (8)
 3 エピローグ                11 (39.7)
14 リュクスポケット          6 (13.2)
 9 ダイイチターミナル        10 (39.1)
 7 カリブメーカー            14 (211.2)
10 ラブラブラブ              7 (15.7)
2回札幌6日 10R 14:50発走 すずらん賞 芝・右 1200m
 1 ケープコッド              1 (1.7)
 7 ヒルノマリブ              2 (4.7)
14 コスモリモーネ            9 (69.5)
10 コスモカルナック          7 (42.8)
 8 カワキタアジン            5 (14)
12 プリンスリターン          3 (7.6)
 3 ダリル                    12 (137.5)
 5 モリデンナイス            14 (285.8)
2回札幌6日 11R 15:25発走 丹頂ステークス 芝・右 2600m
 8 ポンデザール              2 (5.4)
 2 ハナズレジェンド          12 (57.4)
 5 タイセイトレイル          3 (5.7)
 6 マイネルヴンシュ          4 (6.4)
12 ドレッドノータス          10 (16.9)
10 オブリゲーション          13 (90.8)
11 ヤマカツライデン          11 (20.1)
 7 モンドインテロ            5 (9.7)
2回札幌6日 12R 16:05発走 釧路湿原特別 ダート・右 1700m
12 ライジングドラゴン        3 (4.8)
 5 スズカロング              6 (11.7)
 2 レコンキスタ              11 (54.5)
 1 テイエムソレイユ          2 (4.2)
 8 サトノゲイル              7 (12.5)
 4 ヴィーグリーズ            13 (91.5)
14 フクノグリュック          9 (50.1)
10 グランサム                10 (50.9)
2回新潟12日 1R 10:10発走 サラ系障害3歳上未勝利 障害・芝・外->内 2850m
 7 ダノンロッソ              1 (2.2)
11 フラットレー              5 (12.3)
 8 スリーミュージアム        3 (4.6)
 5 レオクイック              6 (18.2)
12 クールエイジア            7 (35.1)
 9 ルグランパントル          2 (3.9)
 6 スマートボムシェル        4 (9.2)
 4 トーセンクロノス          8 (36.4)
2回新潟12日 2R 10:45発走 サラ系3歳未勝利 ダート・左 1800m
10 ロジポルカ                4 (10.8)
 4 モッシュピット            3 (5.8)
 8 ドーバーテソーロ          1 (2.3)
 2 ユイノムサシ              7 (18.2)
 5 サクラザチェンジ          6 (15)
 3 マジックブルーム          12 (48.9)
12 バンディエラ              2 (4.6)
 9 ラインジュピター          10 (41.2)
2回新潟12日 3R 11:15発走 サラ系2歳未勝利 芝・左 2000m
 3 サペラヴィ                3 (6)
12 トロワシャルム            1 (1.8)
10 アイブランコ              9 (61.5)
14 ジチュダケテソーロ        8 (40.2)
11 ドラゴンウォリアー        4 (14.3)
 8 ロッソモラーレ            5 (18.2)
 1 マイヤン                  13 (178.7)
 2 フラッグタワー            6 (33.8)
2回新潟12日 4R 11:45発走 サラ系3歳未勝利 ダート・左 1200m
 5 アペタイザー              1 (3.1)
 7 ルンルンバニラ            3 (5.9)
 9 ボルンタード              6 (15.8)
 2 ハルシオンデイズ          10 (23.8)
15 デルマヴェルサイユ        5 (12.3)
 1 エコロトム                9 (23.2)
 8 カシノラウト              11 (28.4)
10 ウィンズオブゴッド        8 (18.4)
2回新潟12日 5R 12:35発走 サラ系2歳新馬 芝・左 1400m
15 ロードエクスプレス        3 (6.3)
 7 チアチアクラシカ          2 (6)
18 ネバーランド              10 (110.8)
 1 エストロ                  1 (2)
13 プリマジア                9 (71.8)
 6 スピードサウンド          6 (18.9)
16 エリナイトニケ            7 (19)
14 ショウナンサモン          4 (9.1)
2回新潟12日 6R 13:05発走 サラ系3歳未勝利 芝・左・外 1600m
17 パラレルキャリア          1 (1.9)
15 コスモアイトーン          9 (39)
10 カンパーニャ              2 (7.2)
16 コトブキスフェール        7 (22.7)
 1 コスモビックラコグ        5 (11.4)
 9 シバノテンショウ          10 (47.2)
 6 スイートウィスパー        11 (50.6)
 3 リーピングリーズン        8 (24.1)
2回新潟12日 7R 13:35発走 サラ系3歳上1勝クラス(500万円以下) ダート・左 1800m
10 ロードストライク          2 (4.2)
13 コンフィデンス            1 (3.4)
 7 ダンスメーカー            7 (18.1)
 1 ユイノチョッパー          3 (5.8)
 3 モンツァ                  5 (10.9)
 8 ヨクエロマンボ            11 (36.4)
12 ベルゲンハーバー          6 (15.3)
 5 トゥルボー                10 (31.8)
2回新潟12日 8R 14:05発走 サラ系3歳上1勝クラス(500万円以下) 芝・左・外 1600m
18 メッシーナ                1 (1.8)
11 ネオヴィットーリア        5 (18.7)
13 ガロシェ                  2 (3.3)
 8 クィーンビー              12 (114.2)
 5 レディードリー            6 (24.5)
14 カレン                    8 (32.1)
 9 ショウナンハルラ          9 (39.8)
15 ベルキューティ            3 (13.3)
2回新潟12日 9R 14:37発走 岩室温泉特別 ダート・左 1200m
 5 スズカグラーテ            1 (3.2)
14 マラードザレコード        2 (3.8)
 3 アルーアキャロル          3 (5.3)
 7 アルベルティーヌ          4 (8.8)
 6 サンビショップ            14 (116.5)
 4 シュピールカルテ          8 (19.7)
12 トラストロン              6 (13.6)
 9 サンタナブルー            5 (10.8)
2回新潟12日 10R 15:11発走 弥彦特別 芝・左・外 1800m
 5 ウインガナドル            4 (12.6)
 3 アストラサンタン          5 (14.7)
10 アルミレーナ              1 (1.6)
 9 アドマイヤシナイ          8 (63.8)
 1 コーカス                  2 (3.4)
 4 メルヴィンカズマ          3 (8.2)
 2 アーデルワイゼ            6 (42.1)
 7 ドゥリトル                10 (162.2)

2回新潟12日 11R 15:45発走 第55回農林水産省賞典 新潟記念（GIII） 芝・左・外 2000m
 7 ユーキャンスマイル        2 (6.3)
 5 ジナンボー                6 (11.1)
 6 カデナ                    8 (14.2)
15 ブラックスピネル          11 (32)
 4 フランツ                  3 (8.6)
12 ショウナンバッハ          14 (65.3)
16 センテリュオ              4 (9.6)
14 サトノワルキューレ        12 (33.9)
2回新潟12日 12R 16:30発走 雷光特別 芝・直線 1000m
16 ピカピカ                  4 (6.7)
15 エムオールビー            5 (6.7)
18 セイウンアカマイ          2 (4.8)
17 ウインアイルビータ        3 (4.9)
12 ヤマニンベリンダ          9 (26.3)
 6 ヤマニンベルベーヌ        11 (68.1)
10 グラスレガシー            6 (10.6)
13 テンモントム              10 (49.3)
2回小倉12日 1R 10:01発走 サラ系2歳未勝利 ダート・右 1700m
15 キメラヴェリテ            6 (14.7)
 8 スマートラビリンス        5 (10.6)
 2 ジョウショーリード        13 (192.5)
 4 エコロブラッサム          3 (5.9)
 9 ジョーコレット            9 (40.3)
 5 サンビースト              2 (5.6)
14 クリノヴジュアル          10 (41.7)
 6 タガノカスターニャ        4 (6.2)
2回小倉12日 2R 10:35発走 サラ系2歳未勝利 芝・右 1200m
 7 エグレムニ                1 (2.4)
12 カリオストロ              2 (4.2)
 6 アビエルト                7 (17)
 5 ファストボウラー          5 (14.7)
 1 シゲルカセイ              6 (15.1)
 3 イッツマイビジネス        10 (59.9)
 4 アオイスイセイ            3 (7.4)
11 ネクサスアルカナム        4 (9.1)
2回小倉12日 3R 11:05発走 サラ系3歳未勝利 ダート・右 1700m
 1 ザプラウドワンズ          10 (33.5)
 8 プラネットアース          1 (2.6)
13 メメランタン              3 (5.3)
16 エメラルドスピアー        11 (45.9)
12 メイショウウグイス        4 (6)
 6 ニホンピロハビアー        2 (5.2)
 3 エイシンゴエモン          7 (24)
 2 テンナイトパール          15 (208.2)
2回小倉12日 4R 11:35発走 サラ系3歳未勝利 芝・右 1200m
 2 アルバリズム              6 (10.5)
 9 ラハイナヌーン            1 (3.2)
14 メイショウホウジュ        3 (5)
 5 スイートミーティア        5 (10.2)
 4 バニュルス                7 (15.4)
10 ウェーブクリスタル        2 (4.5)
 3 チョウビックリ            13 (100.7)
16 ウインクルマリヒメ        12 (99.6)
2回小倉12日 5R 12:25発走 サラ系2歳新馬 芝・右 1800m
 6 ヴェルトライゼンデ        1 (2.2)
 2 ダンシングリッチー        6 (22.7)
 4 トウカイデュエル          3 (12)
 1 リアンティサージュ        2 (2.6)
10 ビップテッペン            5 (14.8)
11 マジックスピーチ          4 (13.4)
 8 メイショウロールス        9 (63.2)
 5 キングズジェム            11 (116.2)
2回小倉12日 6R 12:55発走 サラ系3歳未勝利 芝・右 2000m
 3 イルマタル                17 (213)
 9 ディオーネプリンス        16 (125.5)
16 ジュベルハフィート        1 (1.8)
 2 レッドルーヴル            5 (11.6)
12 エッセンツァ              2 (8.5)
15 パルメ                    14 (107.5)
 4 オレンジオレンジ          10 (28)
 1 ルッチョーラ              4 (11.4)
2回小倉12日 7R 13:25発走 サラ系3歳上1勝クラス(500万円以下) ダート・右 1700m
 4 ヒロノセンキン            1 (3.2)
 5 オーヴェルニュ            3 (4.5)
 2 ノーチラス                6 (22.6)
16 ハイクアウト              4 (11.2)
13 オーマオ                  9 (31.5)
14 マイヨヴェール            14 (82.6)
 1 アタミ                    5 (14.8)
 7 グーテンモルゲン          12 (41.7)
2回小倉12日 8R 13:55発走 サラ系3歳上1勝クラス(500万円以下) 芝・右 1200m
 1 ブリッツアウェイ          4 (14)
 8 エイシンゾーン            2 (3.9)
 3 プリヴェット              14 (88.8)
 2 ロナ                      1 (2.3)
17 メイショウラバンド        8 (25.2)
 4 リゲイン                  11 (34.6)
15 カーサデルシエロ          3 (8.1)
 7 シエルブラン              12 (50.6)
2回小倉12日 9R 14:25発走 若戸大橋特別 芝・右 1800m
11 ミヤビパーフェクト        6 (11.1)
 3 ガウディウム              2 (4.2)
10 ミアグア                  8 (15.7)
 9 ニューポート              7 (14)
16 ダノンレグナム            5 (11)
 6 デクレアラー              1 (3.6)
12 ヤマニンマヒア            3 (7.3)
 8 パルフェクォーツ          4 (7.3)
2回小倉12日 10R 15:01発走 西日本スポーツ杯 ダート・右 1700m
 9 ゴールドラグーン          1 (3)
 1 サンキュー                5 (16.7)
 4 オンザロックス            4 (7.7)
12 コマビショウ              2 (3.3)
 2 メイショウササユリ        9 (35.6)
 6 シンハラージャ            6 (19.6)
14 タガノエルフ              8 (20.6)
 3 ペガサス                  7 (19.9)
2回小倉12日 11R 15:35発走 第39回小倉2歳ステークス（GIII） 芝・右 1200m
10 マイネルグリット          3 (6.2)
 5 トリプルエース            2 (4.5)
 3 ラウダシオン              4 (8.5)
13 ゼンノジャスタ            8 (29)
 7 カイルアコナ              1 (2.8)
 2 テーオーマルクス          5 (9.7)
12 カリニート                10 (49)
 4 ヒメサマ                  12 (66.8)
2回小倉12日 12R 16:15発走 サラ系3歳上1勝クラス(500万円以下) 芝・右 2600m
14 バイマイサイド            2 (4.4)
 2 ヒラボクメルロー          6 (13)
15 シエラネバダ              9 (21.9)
 9 オーラロード              16 (327.2)
13 サダムラピュタ            5 (7.7)
 7 レオビヨンド              11 (51.7)
 8 アルデエンブレム          13 (102.9)
10 シゲルヒカルダイヤ        10 (36.9)

In [22]:
1-(49/50)**51

0.6431137135146257